### ISSUE TITLE
My friend, you deleted the source code, can you still provide the source code?

### ISSUE THREAD

**Issue by Smithol** [VITA-Group/ChainCoder#1]
1. I want to feel how to compile without error but with low accuracy.

2. I want to know what the syntax tree word divider is. In the end is BPE word segmentation or wordLevel word segmentation, or created a regular word segmentation

**Comment by Wenqing-Zheng** [comment]
Hello,

Thank you for your comments. We've been approved of open sourcing and have just updated the code. For your question, please checkout quick_start_tokenizer.py for more details.
